# Generated by Django 3.2.2 on 2021-05-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='credential',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
